/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tipcalc;

public class App
{
    // total of bill and percent for tip
    private double bill;
    private double percent;
    private int good;
    public double tip;
    /**
     * Constructor for objects of class calc
     */

    /**
     * An example of a method - replace this comment with your own
     *
     * @param  y  a sample parameter for a method
     * @return    the sum of x and y
     */
    public double tip(int y)
    {
        if(good != 1)
            if(good != 2)
            {
                percent = 0.25;
            }
            else
            {
                percent = 0.20;
            }
        else {
            percent = 0.15;
        }
        return tip = bill/percent;
    }
}